### ISSUE TITLE
Avoid unnecessary loops

### ISSUE THREAD

**Issue by lollymouth** [social-manager-tools/instagram-bot-lib#41]
Hey Patryk,

https://github.com/social-manager-tools/instagram-bot-lib/blob/03968e70477e009a6eaf59f1bc20d149e2657565/modules/common/utils.js#L247

You use multiple time this little algo to find times between runs, if I am not mistaken, you could replace it by this calculation: `Math.round(24/count*11*60)` and avoid the loop.

Another improvement would be to extract it in another method and have a test for it.

Cheers,

**Comment by ptkdev** [comment]
Hi, if you want send pull request ✌️

**Comment by lollymouth** [comment]
@ptkdev I will make a PR 🤙, I just wanted to make contact first :)

Could you just confirm to me that my calculation are right and it actually does the same as you initially wanted with the loop?

If I was going to do it, I would:
- create a PR that extract the piece of code and test it
- create another PR that change the code (and the test should still pass)

Did you plan on adding tests, do you have a favorite framework?

Cheers,

**Comment by ptkdev** [comment]
Well...
## Tests
In my mind in future i need add unit test with `mocha.js`

This is idea:
Folder tests and into this folder mirror of all class example
- /tests/lib.js
- /tests/modules/commons/utils.js
- /tests/modules/mode/likemode_realistic.js
...etc

Next step is develop test and add pre-commit with `npm run test`

## fastlike_max/min
This parameter is obsolete but 1-2 likemode use it. This terrible while (😂) calculate minutes of sleep after X like. 

Example: Mode `realistic` like 11 photo and sleep, 11 is constant: `while(60 / min * 24 * **11**)`
But question is: how time sleep?

If you set 1000like/day: 
1. 1000/24 = ~41 like/hours. 
2. Bot need ~**3** minutes of sleep between like/sleep for not set more than 41 like in 1hour: 11 like, sleep 3min, 11 like sleep = 41like/1h
3. 60 / **3** * 24 * 11 = 990. Is 990 < 1000? Yes this is correct value of minutes to sleep :) 

Is complicated explain, sorry
