### ISSUE TITLE
Bot unlikes already liked posts in likemode_realistic

### ISSUE THREAD

**Issue by roNn23** [social-manager-tools/instagram-bot-lib#62]
Sometime the bot get's an liked post and doesn't have it in the database, so it clicks the post and unlikes it with this action.

```
[INFO] like_realistic: username xxxxxx
[INFO] like_realistic: button text before click: <span class="glyphsSpriteHeart__filled__24__red_5 u-__7" aria-label="Unlike"></span>
[INFO] like_realistic: button text after click: <span class="glyphsSpriteHeart__outline__24__grey_9 u-__7" aria-label="Like"></span>
[WARNING] like_realistic: </3
```

**Comment by ptkdev** [comment]
Hi, i merge this pull but not is good solution:
1) Not work with multi-language OS (example: italian windows/chrome)
2) Yes, bot has a cache variable with liked-photo for the current session, see `this.photo liked` but if you restart bot 2-3 fast, this unlike photo :(

**Comment by roNn23** [comment]
Hey @ptkdev. Well, that's correct. Maybe you can parse the class and react to `grey` and `red`?

**Comment by ptkdev** [comment]
@roNn23 yes, at moment bot save all photos on a variable `this.photo_liked` and if after 2h bot go to same photo not click on heart. Imho this is good, but if you restart the bot happen (rare case) the bot unlike the photo if go to same hashtag of before session.

**Comment by roNn23** [comment]
Added a new pull request.
