### ISSUE TITLE
do you think you will add this option

### ISSUE THREAD

**Issue by DiegoRamirez90** [social-manager-tools/instagram-bot-lib#68]
Hello, thank you for this bookstore that works wonderfully

are you going to add this option?

Send direct messages to new followers

Because I think it would be a very interesting option.

Thank you in advance for your answer

**Comment by ptkdev** [comment]
Hi!
This library work with "scraping" of mobile and desktop website of instagram. At moment is impossible send message from pc/website = impossible create this feature. Sorry but this is limit of technology what i use.

**Comment by DiegoRamirez90** [comment]
ok thank you for your answer, I thought it was possible because I found this nodejs library that did it https://github.com/dilame/instagram-private-api

otherwise I will see to couple the library with an api php it may be easier

**Comment by ptkdev** [comment]
I study this library next time, Thanks!
